#!/bin/bash

## Description: Share the frontend
## Usage: frontend-share
## Example: "ddev frontend-share"
## ExecRaw: true
## HostWorkingDir: true

# Function to retrieve the ngrok forward-url
function get_ngrok_url() {
    NGROK_URL=$(curl --silent --max-time 10 http://127.0.0.1:4040/api/tunnels | grep -o '"public_url":"[^"]*"' | cut -d'"' -f4)
    if [[ -z "$NGROK_URL" ]]; then
        echo "Error: Unable to retrieve ngrok URL"
        exit 1
    fi
    echo "Ngrok URL: $NGROK_URL"
}

# Function to update the local Magento base URL with the ngrok forward-url
function update_magento_base_url() {
    local NGROK_URL=$1
    ddev exec bin/magento config:set web/unsecure/base_url "$NGROK_URL/"
    ddev exec bin/magento config:set web/secure/base_url "$NGROK_URL/"
    ddev exec bin/magento cache:flush
    echo "Magento base URL updated to: $NGROK_URL"
}

# Main script execution
if ! pgrep -f "ngrok" > /dev/null; then
    echo "Please run 'ddev share' in a different session before running 'ddev frontend-share'"
    exit 1
fi

get_ngrok_url
update_magento_base_url "$NGROK_URL"
