name: Check Changelog

on: push

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for changelog entry
      run: |
        BASE_BRANCH=$(jq -r .pull_request.base.ref < $GITHUB_EVENT_PATH)
        MERGE_BASE=$(git merge-base HEAD $BASE_BRANCH)
        if ! git diff --name-only $MERGE_BASE HEAD | grep -q 'CHANGELOG.md'; then
          echo "No changelog entry found. Please add an entry to CHANGELOG.md."
          exit 1
        fi
